Repository Flood-UI/flood, pull requests merged in 2018-05, with the labels that each got.

#527 Jsdoc support
  .gitignore
  .jsdoc.json
  README.md
  package.json
Labels: documentation, in progress

#662 new docker issue label
  .github/CONTRIBUTING.md
  .github/labels/docker.png
  .github/labels/labels.md
Labels: documentation

#661 add node 10 (current) test support
  .travis.yml
Labels: test

#664 Iss 646
  README.md
  config.template.js
Labels: documentation

#663 Fix 'Download' button in newer Firefox versions
  client/src/javascript/components/modals/torrent-details-modal/TorrentFiles.js
  client/src/javascript/components/torrent-list/TorrentList.js
Labels: bug

#667 add a link to the wiki
  README.md
Labels: docker, documentation

#671 Update README.md
  README.md
Labels: documentation
